import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {Navbar} from "@/app/components/navbar/navbar";
import {Footer} from "@/app/components/footer/footer";
import {ColorSchemeScript,MantineProvider} from "@mantine/core";
import AuthProvider from "@/app/hooks/auth";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <head>
        <ColorSchemeScript defaultColorScheme="dark"/>
    </head>
    <body className={inter.className}>
    <div className="flex flex-col min-h-screen bg-amber-200">
        <Navbar/>
-      <main className="flex-grow">{children}
          </main>
      </div>
      <Footer/>
      </body>
    </html>
  )
}
